name: Hyrax
version: '${version}'
main: io.github.takorojo.hyrax.Hyrax
api-version: 1.19
depend: [ Multiverse-Core ]
softdepend: [ LuckPerms ]
authors: [ takorojo ]
description: A backup utility for Minecraft worlds on Bukkit/Paper servers
website: https://github.com/takorojo/hyrax
commands:
  backup-world:
    description: Back up the current world to the server's backup directory
    usage: /backup-world
  restore-world:
    description: Restore the current world's latest backup if there is one
    usage: /restore-world
